dist: trusty
language: python

cache: pip

env:
  - $TESTS_TO_RUN=advanced_tests
  - $TESTS_TO_RUN=tests

python:
  - "2.7"
  - "3.6"

install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls nose tables
  - pip install --only-binary=numpy,scipy,pandas -r requirements.txt
  - pip install lightgbm keras tensorflow catboost xgboost

script:
  - nosetests $TESTS_TO_RUN

  - coveralls
