sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# Command to install dependencies
install:
  - TEST_DIR=$PWD
  - sudo apt-get update

  #  Install LightGBM
  - sudo apt-get install -y libopenmpi-dev openmpi-bin build-essential libtcmalloc-minimal4 ocl-icd-opencl-dev
  - export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
  - git clone --recursive https://github.com/Microsoft/LightGBM LightGBM
  - cd LightGBM && mkdir build && cd build && cmake .. && make -j
  # Exit out of the build dir up a level to where python-package is
  - cd ..

  # We need scipy installed to get the python version of lightgbm.
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy

  # Install the python part of LightGBM now that we have scipy
  - cd python-package
  - python setup.py install
  # Move back to the directory we want to run our tests in, out of the LightGBM build directories
  - cd $TEST_DIR

  # Install XGBoost
  - git clone --recursive https://github.com/dmlc/xgboost
  - cd xgboost; make -j4
  - cd python-package
  - python setup.py install
  - cd $TEST_DIR


  - pip install coveralls
  - pip install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp35-cp35m-linux_x86_64.whl;
    fi
  - pip install keras
  - pip install h5py
# Command to run tests
script: nosetests -v --with-coverage --cover-package auto_ml tests

after_success:
  coveralls
