sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.5"

# Command to install dependencies
install:
  - echo $PWD
  # These first three sections taken directly from https://github.com/ArdalanM/pyLightGBM/blob/master/.travis.yml on 3-10-17
  # Installing LightGBM on travis is proving challenging, so I will defer to someone who's gotten it working successfully.
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  #  Install LightGBM
  - sudo apt-get install -y libopenmpi-dev openmpi-bin build-essential
  - git clone --recursive https://github.com/Microsoft/LightGBM $HOME/LightGBM
  - cd $HOME/LightGBM && mkdir build && cd build && cmake .. && make -j
  - export LIGHTGBM_EXEC="$HOME/LightGBM/lightgbm"
  - echo -e "LighGBM executable:\n$(echo $LIGHTGBM_EXEC)"
  - cd $TRAVIS_BUILD_DIR

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # This begins the section I wrote specifically for auto_ml
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
  - pip install dill scikit-learn scipy python-dateutil pandas pathos
  - echo $PWD
  # - git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
  # - mkdir build ; cd build
  # - cmake ..
  # - make -j
# Command to run tests
script: nosetests -v --with-coverage --cover-package auto_ml tests

after_success:
  coveralls
