language: python
python:
  - "2.7"
  - "3.5"

# Command to install dependencies
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
# Command to run tests
script: travis_wait nosetests -v tests