sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.5"

# Command to install dependencies
install:
  - TEST_DIR=$PWD
  - sudo apt-get update

  #  Install LightGBM
  - sudo apt-get install -y libopenmpi-dev openmpi-bin build-essential
  - git clone --recursive https://github.com/Microsoft/LightGBM LightGBM
  - cd LightGBM && mkdir build && cd build && cmake .. && make -j
  # Exit out of the build dir up a level to where python-package is
  - cd ..

  # We need scipy installed to get the python version of lightgbm.
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy

  # Install the python part of LightGBM now that we have scipy
  - cd python-package
  - python setup.py install
  # Move back to the directory we want to run our tests in, out of the LightGBM build directories
  - cd $TEST_DIR

  - pip install coveralls
  - pip install -r requirements.txt

# Command to run tests
script: nosetests -v --with-coverage --cover-package auto_ml tests

after_success:
  coveralls
