language: python
python:
  - "2.7"
  - "3.5"

# Command to install dependencies
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy,scipy numpy scipy
  # - pip install -r requirements.txt
  - pip install tensorflow
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp27-none-linux_x86_64.whl;
  #   elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
  #     pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp35-cp35m-linux_x86_64.whl;
  #   fi
  - pip install keras
# Command to run tests
script: python keras_import.py
# script: nosetests -v --with-coverage --cover-package auto_ml tests

after_success:
  coveralls
