language: python
python:
  - "2.7"
  - "3.5"

# Command to install dependencies
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
# Command to run tests
script: nosetests -v --with-coverage --cover-package auto_ml tests

after_success:
  coveralls