sudo: required
dist: trusty
language: python

matrix:
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  env:
    - TESTS_TO_RUN=tests
    - TESTS_TO_RUN=advanced_tests

install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls
  - pip install nose
  - pip install --only-binary=numpy,scipy,pandas -r requirements.txt

  # For reading and writing to HDF5 (how we store some of our datasets) we need tables
  - pip install tables

script:

  - if [ 'advanced' in $TESTS_TO_RUN ];
    then pip install lightgbm keras tensorflow catboost xgboost;
    fi
  - nosetests $TESTS_TO_RUN

  # - nosetests advanced_tests

  - coveralls
